export const GPU_DATABASE = [
  // ==========================================
  // 1. INTEGRATED GRAPHICS (INTEL & AMD)
  // ==========================================
  {
    id: "intel-hd-3000",
    name: "Intel HD Graphics 3000",
    brand: "Intel",
    family: "Intel HD Graphics",
    tier: "integrated legacy",
    vram: 0,
    score: 8,
    gaming: 5,
    ai: 1,
    releaseYear: 2011,
    aliases: ["intel hd 3000", "intel hd graphics 3000", "hdgraphics3000", "hd graphics 3000", "hd 3000"]
  },
  {
    id: "intel-hd-4000",
    name: "Intel HD Graphics 4000",
    brand: "Intel",
    family: "Intel HD Graphics",
    tier: "integrated legacy",
    vram: 0,
    score: 12,
    gaming: 9,
    ai: 2,
    releaseYear: 2012,
    aliases: ["intel hd 4000", "intel hd graphics 4000", "hdgraphics4000", "hd graphics 4000", "hd 4000"]
  },
  {
    id: "intel-hd-4600",
    name: "Intel HD Graphics 4600",
    brand: "Intel",
    family: "Intel HD Graphics",
    tier: "integrated legacy",
    vram: 0,
    score: 14,
    gaming: 11,
    ai: 3,
    releaseYear: 2013,
    aliases: ["intel hd 4600", "intel hd graphics 4600", "hdgraphics4600", "hd graphics 4600", "hd 4600"]
  },
  {
    id: "intel-hd-520",
    name: "Intel HD Graphics 520",
    brand: "Intel",
    family: "Intel HD Graphics",
    tier: "integrated legacy",
    vram: 0,
    score: 18,
    gaming: 14,
    ai: 4,
    releaseYear: 2015,
    aliases: ["intel hd 520", "hd graphics 520", "hdgraphics520", "intelhdgraphics520", "hd 520"]
  },
  {
    id: "intel-uhd-600",
    name: "Intel UHD Graphics 600",
    brand: "Intel",
    family: "Intel UHD Graphics",
    tier: "integrated entry",
    vram: 0,
    score: 12,
    gaming: 9,
    ai: 3,
    releaseYear: 2017,
    aliases: ["intel uhd 600", "uhd graphics 600", "uhd 600", "uhdgraphics600"]
  },
  {
    id: "intel-uhd-620",
    name: "Intel UHD Graphics 620",
    brand: "Intel",
    family: "Intel UHD Graphics",
    tier: "integrated",
    vram: 0,
    score: 21,
    gaming: 16,
    ai: 5,
    releaseYear: 2017,
    aliases: ["intel uhd 620", "uhd graphics 620", "uhd 620", "uhdgraphics620"]
  },
  {
    id: "intel-uhd-630",
    name: "Intel UHD Graphics 630",
    brand: "Intel",
    family: "Intel UHD Graphics",
    tier: "integrated",
    vram: 0,
    score: 23,
    gaming: 18,
    ai: 6,
    releaseYear: 2017,
    aliases: ["intel uhd 630", "uhd graphics 630", "uhd 630", "uhdgraphics630"]
  },
  {
    id: "intel-uhd-730",
    name: "Intel UHD Graphics 730",
    brand: "Intel",
    family: "Intel UHD Graphics",
    tier: "integrated",
    vram: 0,
    score: 26,
    gaming: 20,
    ai: 8,
    releaseYear: 2021,
    aliases: ["intel uhd 730", "uhd graphics 730", "uhd 730", "uhdgraphics730"]
  },
  {
    id: "intel-uhd-770",
    name: "Intel UHD Graphics 770",
    brand: "Intel",
    family: "Intel UHD Graphics",
    tier: "integrated plus",
    vram: 0,
    score: 30,
    gaming: 24,
    ai: 10,
    releaseYear: 2021,
    aliases: ["intel uhd 770", "uhd graphics 770", "uhd 770", "uhdgraphics770"]
  },
  {
    id: "intel-iris-xe",
    name: "Intel Iris Xe Graphics",
    brand: "Intel",
    family: "Intel Iris Xe",
    tier: "integrated plus",
    vram: 0,
    score: 37,
    gaming: 31,
    ai: 14,
    releaseYear: 2020,
    aliases: ["intel iris xe", "iris xe", "irisxe", "iris xe graphics"]
  },
  {
    id: "intel-arc-graphics",
    name: "Intel Arc Graphics (iGPU)",
    brand: "Intel",
    family: "Intel Arc",
    tier: "integrated ultra",
    vram: 0,
    score: 44,
    gaming: 42,
    ai: 32,
    releaseYear: 2023,
    aliases: ["intel arc igpu", "arc graphics", "intel arc graphics mobile"]
  },
  {
    id: "amd-vega-3",
    name: "AMD Radeon Vega 3",
    brand: "AMD",
    family: "AMD Vega",
    tier: "integrated entry",
    vram: 0,
    score: 18,
    gaming: 14,
    ai: 4,
    releaseYear: 2018,
    aliases: ["vega 3", "radeon vega 3", "amd vega 3"]
  },
  {
    id: "amd-vega-6",
    name: "AMD Radeon Vega 6",
    brand: "AMD",
    family: "AMD Vega",
    tier: "integrated",
    vram: 0,
    score: 25,
    gaming: 21,
    ai: 6,
    releaseYear: 2020,
    aliases: ["vega 6", "radeon vega 6", "amd vega 6"]
  },
  {
    id: "amd-vega-8",
    name: "AMD Radeon Vega 8",
    brand: "AMD",
    family: "AMD Vega",
    tier: "integrated plus",
    vram: 0,
    score: 31,
    gaming: 27,
    ai: 9,
    releaseYear: 2018,
    aliases: ["vega 8", "radeon vega 8", "amd vega 8"]
  },
  {
    id: "amd-vega-10",
    name: "AMD Radeon RX Vega 10",
    brand: "AMD",
    family: "AMD Vega",
    tier: "integrated plus",
    vram: 0,
    score: 34,
    gaming: 30,
    ai: 10,
    releaseYear: 2017,
    aliases: ["vega 10", "radeon vega 10", "rx vega 10", "amd vega 10"]
  },
  {
    id: "amd-radeon-610m",
    name: "AMD Radeon 610M",
    brand: "AMD",
    family: "AMD Radeon",
    tier: "integrated entry",
    vram: 0,
    score: 22,
    gaming: 18,
    ai: 8,
    releaseYear: 2022,
    aliases: ["610m", "radeon 610m", "amd 610m"]
  },
  {
    id: "amd-radeon-660m",
    name: "AMD Radeon 660M",
    brand: "AMD",
    family: "AMD Radeon",
    tier: "integrated plus",
    vram: 0,
    score: 36,
    gaming: 34,
    ai: 18,
    releaseYear: 2022,
    aliases: ["660m", "radeon 660m", "amd 660m"]
  },
  {
    id: "amd-radeon-680m",
    name: "AMD Radeon 680M",
    brand: "AMD",
    family: "AMD Radeon",
    tier: "integrated ultra",
    vram: 0,
    score: 41,
    gaming: 39,
    ai: 24,
    releaseYear: 2022,
    aliases: ["680m", "radeon 680m", "amd 680m"]
  },
  {
    id: "amd-radeon-760m",
    name: "AMD Radeon 760M",
    brand: "AMD",
    family: "AMD Radeon",
    tier: "integrated plus",
    vram: 0,
    score: 38,
    gaming: 36,
    ai: 22,
    releaseYear: 2023,
    aliases: ["760m", "radeon 760m", "amd 760m"]
  },
  {
    id: "amd-radeon-780m",
    name: "AMD Radeon 780M",
    brand: "AMD",
    family: "AMD Radeon",
    tier: "integrated ultra",
    vram: 0,
    score: 42,
    gaming: 40,
    ai: 26,
    releaseYear: 2023,
    aliases: ["780m", "radeon 780m", "amd 780m"]
  },
  {
    id: "amd-radeon-890m",
    name: "AMD Radeon 890M",
    brand: "AMD",
    family: "AMD Radeon",
    tier: "integrated flagship",
    vram: 0,
    score: 49,
    gaming: 48,
    ai: 38,
    releaseYear: 2024,
    aliases: ["890m", "radeon 890m", "amd 890m"]
  },

  // ==========================================
  // 2. APPLE SILICON GPUs
  // ==========================================
  {
    id: "apple-m1-gpu",
    name: "Apple M1 GPU",
    brand: "Apple",
    family: "Apple Silicon",
    tier: "integrated ultra",
    vram: 0,
    score: 45,
    gaming: 40,
    ai: 50,
    releaseYear: 2020,
    aliases: ["apple m1 gpu", "m1 gpu", "macbook m1 gpu"]
  },
  {
    id: "apple-m2-gpu",
    name: "Apple M2 GPU",
    brand: "Apple",
    family: "Apple Silicon",
    tier: "integrated ultra",
    vram: 0,
    score: 52,
    gaming: 46,
    ai: 60,
    releaseYear: 2022,
    aliases: ["apple m2 gpu", "m2 gpu", "macbook m2 gpu"]
  },
  {
    id: "apple-m3-gpu",
    name: "Apple M3 GPU",
    brand: "Apple",
    family: "Apple Silicon",
    tier: "integrated flagship",
    vram: 0,
    score: 60,
    gaming: 55,
    ai: 70,
    releaseYear: 2023,
    aliases: ["apple m3 gpu", "m3 gpu", "macbook m3 gpu"]
  },
  {
    id: "apple-m4-gpu",
    name: "Apple M4 GPU",
    brand: "Apple",
    family: "Apple Silicon",
    tier: "integrated flagship",
    vram: 0,
    score: 68,
    gaming: 62,
    ai: 82,
    releaseYear: 2024,
    aliases: ["apple m4 gpu", "m4 gpu", "ipad pro m4 gpu", "macbook m4 gpu"]
  },

  // ==========================================
  // 3. LAPTOP / MOBILE DISCRETE GPUs
  // ==========================================
  {
    id: "nvidia-mx150",
    name: "NVIDIA GeForce MX150",
    brand: "NVIDIA",
    family: "MX Series",
    tier: "entry mobile",
    vram: 2,
    score: 26,
    gaming: 24,
    ai: 6,
    releaseYear: 2017,
    aliases: ["mx150", "geforce mx150", "nvidia mx150", "mx 150"]
  },
  {
    id: "nvidia-mx250",
    name: "NVIDIA GeForce MX250",
    brand: "NVIDIA",
    family: "MX Series",
    tier: "entry mobile",
    vram: 2,
    score: 28,
    gaming: 26,
    ai: 7,
    releaseYear: 2019,
    aliases: ["mx250", "geforce mx250", "nvidia mx250", "mx 250"]
  },
  {
    id: "nvidia-mx350",
    name: "NVIDIA GeForce MX350",
    brand: "NVIDIA",
    family: "MX Series",
    tier: "entry mobile",
    vram: 2,
    score: 32,
    gaming: 30,
    ai: 8,
    releaseYear: 2020,
    aliases: ["mx350", "geforce mx350", "nvidia mx350", "mx 350"]
  },
  {
    id: "nvidia-mx450",
    name: "NVIDIA GeForce MX450",
    brand: "NVIDIA",
    family: "MX Series",
    tier: "entry mobile",
    vram: 2,
    score: 36,
    gaming: 35,
    ai: 10,
    releaseYear: 2020,
    aliases: ["mx450", "geforce mx450", "nvidia mx450", "mx 450"]
  },
  {
    id: "nvidia-gtx-1650-mobile",
    name: "NVIDIA GeForce GTX 1650 (Laptop)",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry mobile discrete",
    vram: 4,
    score: 45,
    gaming: 46,
    ai: 16,
    releaseYear: 2019,
    aliases: ["gtx 1650 laptop", "gtx 1650 mobile", "geforce gtx 1650 laptop"]
  },
  {
    id: "nvidia-rtx-2050-mobile",
    name: "NVIDIA GeForce RTX 2050 (Laptop)",
    brand: "NVIDIA",
    family: "RTX 20 Series",
    tier: "entry ray tracing mobile",
    vram: 4,
    score: 52,
    gaming: 52,
    ai: 30,
    releaseYear: 2021,
    aliases: ["rtx 2050 laptop", "rtx 2050 mobile", "geforce rtx 2050 laptop", "rtx 2050"]
  },
  {
    id: "nvidia-rtx-3050-mobile",
    name: "NVIDIA GeForce RTX 3050 (Laptop)",
    brand: "NVIDIA",
    family: "RTX 30 Series",
    tier: "mainstream ray tracing mobile",
    vram: 4,
    score: 58,
    gaming: 60,
    ai: 40,
    releaseYear: 2021,
    aliases: ["rtx 3050 laptop", "rtx 3050 mobile", "geforce rtx 3050 laptop"]
  },
  {
    id: "nvidia-rtx-4050-mobile",
    name: "NVIDIA GeForce RTX 4050 (Laptop)",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "efficient ray tracing mobile",
    vram: 6,
    score: 70,
    gaming: 72,
    ai: 55,
    releaseYear: 2023,
    aliases: ["rtx 4050 laptop", "rtx 4050 mobile", "geforce rtx 4050 laptop", "rtx 4050"]
  },
  {
    id: "nvidia-rtx-4060-mobile",
    name: "NVIDIA GeForce RTX 4060 (Laptop)",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "performance ray tracing mobile",
    vram: 8,
    score: 78,
    gaming: 80,
    ai: 65,
    releaseYear: 2023,
    aliases: ["rtx 4060 laptop", "rtx 4060 mobile", "geforce rtx 4060 laptop"]
  },
  {
    id: "nvidia-rtx-4070-mobile",
    name: "NVIDIA GeForce RTX 4070 (Laptop)",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "enthusiast ray tracing mobile",
    vram: 8,
    score: 84,
    gaming: 85,
    ai: 72,
    releaseYear: 2023,
    aliases: ["rtx 4070 laptop", "rtx 4070 mobile", "geforce rtx 4070 laptop"]
  },

  // ==========================================
  // 4. NVIDIA DESKTOP GPUs (GTX & RTX)
  // ==========================================
  {
    id: "nvidia-gt-710",
    name: "NVIDIA GeForce GT 710",
    brand: "NVIDIA",
    family: "GT Series",
    tier: "basic display",
    vram: 2,
    score: 8,
    gaming: 5,
    ai: 1,
    releaseYear: 2016,
    aliases: ["gt 710", "gt710", "geforce gt 710", "nvidia gt 710"]
  },
  {
    id: "nvidia-gt-730",
    name: "NVIDIA GeForce GT 730",
    brand: "NVIDIA",
    family: "GT Series",
    tier: "basic display",
    vram: 2,
    score: 10,
    gaming: 8,
    ai: 2,
    releaseYear: 2014,
    aliases: ["gt 730", "gt730", "geforce gt 730", "nvidia gt 730"]
  },
  {
    id: "nvidia-gtx-750-ti",
    name: "NVIDIA GeForce GTX 750 Ti",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete",
    vram: 2,
    score: 24,
    gaming: 22,
    ai: 4,
    releaseYear: 2014,
    aliases: ["gtx 750 ti", "gtx750ti", "geforce gtx 750 ti"]
  },
  {
    id: "nvidia-gtx-950",
    name: "NVIDIA GeForce GTX 950",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete",
    vram: 2,
    score: 30,
    gaming: 28,
    ai: 6,
    releaseYear: 2015,
    aliases: ["gtx 950", "gtx950", "geforce gtx 950"]
  },
  {
    id: "nvidia-gtx-960",
    name: "NVIDIA GeForce GTX 960",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete",
    vram: 4,
    score: 35,
    gaming: 34,
    ai: 8,
    releaseYear: 2015,
    aliases: ["gtx 960", "gtx960", "geforce gtx 960"]
  },
  {
    id: "nvidia-gtx-1050",
    name: "NVIDIA GeForce GTX 1050",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete",
    vram: 2,
    score: 39,
    gaming: 38,
    ai: 12,
    releaseYear: 2016,
    aliases: ["gtx 1050", "gtx1050", "geforce gtx 1050"]
  },
  {
    id: "nvidia-gtx-1050-ti",
    name: "NVIDIA GeForce GTX 1050 Ti",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete",
    vram: 4,
    score: 43,
    gaming: 44,
    ai: 14,
    releaseYear: 2016,
    aliases: ["gtx 1050 ti", "gtx1050ti", "geforce gtx 1050 ti"]
  },
  {
    id: "nvidia-gtx-1060",
    name: "NVIDIA GeForce GTX 1060",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "midrange discrete",
    vram: 6,
    score: 45,
    gaming: 48,
    ai: 18,
    releaseYear: 2016,
    aliases: ["gtx 1060", "gtx1060", "geforce gtx 1060"]
  },
  {
    id: "nvidia-gtx-1070",
    name: "NVIDIA GeForce GTX 1070",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "performance discrete",
    vram: 8,
    score: 58,
    gaming: 62,
    ai: 26,
    releaseYear: 2016,
    aliases: ["gtx 1070", "gtx1070", "geforce gtx 1070"]
  },
  {
    id: "nvidia-gtx-1080",
    name: "NVIDIA GeForce GTX 1080",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "performance discrete",
    vram: 8,
    score: 70,
    gaming: 74,
    ai: 34,
    releaseYear: 2016,
    aliases: ["gtx 1080", "gtx1080", "geforce gtx 1080"]
  },
  {
    id: "nvidia-gtx-1650",
    name: "NVIDIA GeForce GTX 1650",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete",
    vram: 4,
    score: 50,
    gaming: 51,
    ai: 20,
    releaseYear: 2019,
    aliases: ["gtx 1650", "gtx1650", "geforce gtx 1650"]
  },
  {
    id: "nvidia-gtx-1650-super",
    name: "NVIDIA GeForce GTX 1650 Super",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "entry discrete plus",
    vram: 4,
    score: 56,
    gaming: 58,
    ai: 24,
    releaseYear: 2019,
    aliases: ["gtx 1650 super", "gtx1650super", "geforce gtx 1650 super"]
  },
  {
    id: "nvidia-gtx-1660-super",
    name: "NVIDIA GeForce GTX 1660 Super",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "midrange discrete",
    vram: 6,
    score: 61,
    gaming: 63,
    ai: 28,
    releaseYear: 2019,
    aliases: ["gtx 1660 super", "gtx1660super", "gtx 1660"]
  },
  {
    id: "nvidia-gtx-1660-ti",
    name: "NVIDIA GeForce GTX 1660 Ti",
    brand: "NVIDIA",
    family: "GTX Series",
    tier: "midrange discrete",
    vram: 6,
    score: 63,
    gaming: 65,
    ai: 29,
    releaseYear: 2019,
    aliases: ["gtx 1660 ti", "gtx1660ti", "geforce gtx 1660 ti"]
  },
  {
    id: "nvidia-rtx-2060",
    name: "NVIDIA GeForce RTX 2060",
    brand: "NVIDIA",
    family: "RTX 20 Series",
    tier: "midrange ray tracing",
    vram: 6,
    score: 66,
    gaming: 68,
    ai: 45,
    releaseYear: 2019,
    aliases: ["rtx 2060", "rtx2060", "geforce rtx 2060"]
  },
  {
    id: "nvidia-rtx-3050",
    name: "NVIDIA GeForce RTX 3050",
    brand: "NVIDIA",
    family: "RTX 30 Series",
    tier: "entry ray tracing",
    vram: 8,
    score: 68,
    gaming: 68,
    ai: 50,
    releaseYear: 2022,
    aliases: ["rtx 3050", "rtx3050", "geforce rtx 3050"]
  },
  {
    id: "nvidia-rtx-3060",
    name: "NVIDIA GeForce RTX 3060",
    brand: "NVIDIA",
    family: "RTX 30 Series",
    tier: "mainstream ray tracing",
    vram: 12,
    score: 75,
    gaming: 76,
    ai: 62,
    releaseYear: 2021,
    aliases: ["rtx 3060", "rtx3060", "geforce rtx 3060"]
  },
  {
    id: "nvidia-rtx-3070",
    name: "NVIDIA GeForce RTX 3070",
    brand: "NVIDIA",
    family: "RTX 30 Series",
    tier: "performance ray tracing",
    vram: 8,
    score: 83,
    gaming: 85,
    ai: 70,
    releaseYear: 2020,
    aliases: ["rtx 3070", "rtx3070", "geforce rtx 3070"]
  },
  {
    id: "nvidia-rtx-3080",
    name: "NVIDIA GeForce RTX 3080",
    brand: "NVIDIA",
    family: "RTX 30 Series",
    tier: "enthusiast ray tracing",
    vram: 10,
    score: 88,
    gaming: 90,
    ai: 80,
    releaseYear: 2020,
    aliases: ["rtx 3080", "rtx3080", "geforce rtx 3080"]
  },
  {
    id: "nvidia-rtx-3090",
    name: "NVIDIA GeForce RTX 3090",
    brand: "NVIDIA",
    family: "RTX 30 Series",
    tier: "flagship ray tracing",
    vram: 24,
    score: 95,
    gaming: 95,
    ai: 95,
    releaseYear: 2020,
    aliases: ["rtx 3090", "rtx3090", "geforce rtx 3090"]
  },
  {
    id: "nvidia-rtx-4060",
    name: "NVIDIA GeForce RTX 4060",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "efficient ray tracing",
    vram: 8,
    score: 80,
    gaming: 82,
    ai: 72,
    releaseYear: 2023,
    aliases: ["rtx 4060", "rtx4060", "geforce rtx 4060"]
  },
  {
    id: "nvidia-rtx-4060-ti",
    name: "NVIDIA GeForce RTX 4060 Ti",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "efficient performance ray tracing",
    vram: 8,
    score: 84,
    gaming: 86,
    ai: 76,
    releaseYear: 2023,
    aliases: ["rtx 4060 ti", "rtx4060ti", "geforce rtx 4060 ti"]
  },
  {
    id: "nvidia-rtx-4070",
    name: "NVIDIA GeForce RTX 4070",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "performance ray tracing",
    vram: 12,
    score: 89,
    gaming: 91,
    ai: 82,
    releaseYear: 2023,
    aliases: ["rtx 4070", "rtx4070", "geforce rtx 4070"]
  },
  {
    id: "nvidia-rtx-4080",
    name: "NVIDIA GeForce RTX 4080",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "enthusiast ray tracing",
    vram: 16,
    score: 96,
    gaming: 97,
    ai: 96,
    releaseYear: 2022,
    aliases: ["rtx 4080", "rtx4080", "geforce rtx 4080"]
  },
  {
    id: "nvidia-rtx-4090",
    name: "NVIDIA GeForce RTX 4090",
    brand: "NVIDIA",
    family: "RTX 40 Series",
    tier: "flagship ray tracing",
    vram: 24,
    score: 100,
    gaming: 100,
    ai: 100,
    releaseYear: 2022,
    aliases: ["rtx 4090", "rtx4090", "geforce rtx 4090"]
  },
  {
    id: "nvidia-rtx-5070",
    name: "NVIDIA GeForce RTX 5070",
    brand: "NVIDIA",
    family: "RTX 50 Series",
    tier: "next-gen ray tracing",
    vram: 12,
    score: 92,
    gaming: 94,
    ai: 92,
    releaseYear: 2025,
    aliases: ["rtx 5070", "rtx5070", "geforce rtx 5070"]
  },
  {
    id: "nvidia-rtx-5080",
    name: "NVIDIA GeForce RTX 5080",
    brand: "NVIDIA",
    family: "RTX 50 Series",
    tier: "next-gen enthusiast",
    vram: 16,
    score: 98,
    gaming: 98,
    ai: 98,
    releaseYear: 2025,
    aliases: ["rtx 5080", "rtx5080", "geforce rtx 5080"]
  },
  {
    id: "nvidia-rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    brand: "NVIDIA",
    family: "RTX 50 Series",
    tier: "flagship ray tracing",
    vram: 32,
    score: 100,
    gaming: 100,
    ai: 100,
    releaseYear: 2025,
    aliases: ["rtx 5090", "rtx5090", "geforce rtx 5090"]
  },

  // ==========================================
  // 5. AMD RADEON RX & DESKTOP GPUs
  // ==========================================
  {
    id: "amd-rx-550",
    name: "AMD Radeon RX 550",
    brand: "AMD",
    family: "RX Series",
    tier: "entry discrete",
    vram: 4,
    score: 28,
    gaming: 26,
    ai: 5,
    releaseYear: 2017,
    aliases: ["rx 550", "rx550", "radeon rx 550"]
  },
  {
    id: "amd-rx-570",
    name: "AMD Radeon RX 570",
    brand: "AMD",
    family: "RX Series",
    tier: "legacy discrete",
    vram: 8,
    score: 50,
    gaming: 52,
    ai: 20,
    releaseYear: 2017,
    aliases: ["rx 570", "rx570", "radeon rx 570"]
  },
  {
    id: "amd-rx-580",
    name: "AMD Radeon RX 580",
    brand: "AMD",
    family: "RX Series",
    tier: "legacy discrete",
    vram: 8,
    score: 56,
    gaming: 58,
    ai: 24,
    releaseYear: 2017,
    aliases: ["rx 580", "rx580", "radeon rx 580"]
  },
  {
    id: "amd-rx-5500-xt",
    name: "AMD Radeon RX 5500 XT",
    brand: "AMD",
    family: "AMD RDNA",
    tier: "entry discrete",
    vram: 8,
    score: 58,
    gaming: 60,
    ai: 26,
    releaseYear: 2019,
    aliases: ["rx 5500 xt", "rx5500xt", "radeon rx 5500 xt"]
  },
  {
    id: "amd-rx-5700-xt",
    name: "AMD Radeon RX 5700 XT",
    brand: "AMD",
    family: "AMD RDNA",
    tier: "mainstream discrete",
    vram: 8,
    score: 72,
    gaming: 74,
    ai: 38,
    releaseYear: 2019,
    aliases: ["rx 5700 xt", "rx5700xt", "radeon rx 5700 xt"]
  },
  {
    id: "amd-rx-6500-xt",
    name: "AMD Radeon RX 6500 XT",
    brand: "AMD",
    family: "AMD RDNA 2",
    tier: "entry discrete",
    vram: 4,
    score: 55,
    gaming: 56,
    ai: 25,
    releaseYear: 2022,
    aliases: ["rx 6500 xt", "rx6500xt", "radeon rx 6500 xt"]
  },
  {
    id: "amd-rx-6600",
    name: "AMD Radeon RX 6600",
    brand: "AMD",
    family: "AMD RDNA 2",
    tier: "mainstream discrete",
    vram: 8,
    score: 70,
    gaming: 73,
    ai: 45,
    releaseYear: 2021,
    aliases: ["rx 6600", "rx6600", "radeon rx 6600"]
  },
  {
    id: "amd-rx-6700-xt",
    name: "AMD Radeon RX 6700 XT",
    brand: "AMD",
    family: "AMD RDNA 2",
    tier: "performance discrete",
    vram: 12,
    score: 80,
    gaming: 82,
    ai: 55,
    releaseYear: 2021,
    aliases: ["rx 6700 xt", "rx6700xt", "radeon rx 6700 xt"]
  },
  {
    id: "amd-rx-6800-xt",
    name: "AMD Radeon RX 6800 XT",
    brand: "AMD",
    family: "AMD RDNA 2",
    tier: "enthusiast discrete",
    vram: 16,
    score: 88,
    gaming: 90,
    ai: 62,
    releaseYear: 2020,
    aliases: ["rx 6800 xt", "rx6800xt", "radeon rx 6800 xt"]
  },
  {
    id: "amd-rx-6900-xt",
    name: "AMD Radeon RX 6900 XT",
    brand: "AMD",
    family: "AMD RDNA 2",
    tier: "flagship discrete",
    vram: 16,
    score: 92,
    gaming: 94,
    ai: 68,
    releaseYear: 2020,
    aliases: ["rx 6900 xt", "rx6900xt", "radeon rx 6900 xt"]
  },
  {
    id: "amd-rx-7600",
    name: "AMD Radeon RX 7600",
    brand: "AMD",
    family: "AMD RDNA 3",
    tier: "mainstream discrete",
    vram: 8,
    score: 78,
    gaming: 80,
    ai: 54,
    releaseYear: 2023,
    aliases: ["rx 7600", "rx7600", "radeon rx 7600"]
  },
  {
    id: "amd-rx-7700-xt",
    name: "AMD Radeon RX 7700 XT",
    brand: "AMD",
    family: "AMD RDNA 3",
    tier: "performance discrete",
    vram: 12,
    score: 84,
    gaming: 86,
    ai: 60,
    releaseYear: 2023,
    aliases: ["rx 7700 xt", "rx7700xt", "radeon rx 7700 xt"]
  },
  {
    id: "amd-rx-7800-xt",
    name: "AMD Radeon RX 7800 XT",
    brand: "AMD",
    family: "AMD RDNA 3",
    tier: "performance discrete",
    vram: 16,
    score: 88,
    gaming: 90,
    ai: 68,
    releaseYear: 2023,
    aliases: ["rx 7800 xt", "rx7800xt", "radeon rx 7800 xt"]
  },
  {
    id: "amd-rx-7900-xt",
    name: "AMD Radeon RX 7900 XT",
    brand: "AMD",
    family: "AMD RDNA 3",
    tier: "enthusiast discrete",
    vram: 20,
    score: 93,
    gaming: 94,
    ai: 74,
    releaseYear: 2022,
    aliases: ["rx 7900 xt", "rx7900xt", "radeon rx 7900 xt"]
  },
  {
    id: "amd-rx-7900-xtx",
    name: "AMD Radeon RX 7900 XTX",
    brand: "AMD",
    family: "AMD RDNA 3",
    tier: "flagship discrete",
    vram: 24,
    score: 95,
    gaming: 96,
    ai: 78,
    releaseYear: 2022,
    aliases: ["rx 7900 xtx", "rx7900xtx", "radeon rx 7900 xtx"]
  },

  // ==========================================
  // 6. INTEL ARC DESKTOP GPUs
  // ==========================================
  {
    id: "intel-arc-a380",
    name: "Intel Arc A380",
    brand: "Intel",
    family: "Intel Arc",
    tier: "entry discrete",
    vram: 6,
    score: 48,
    gaming: 47,
    ai: 28,
    releaseYear: 2022,
    aliases: ["arc a380", "intel arc a380", "a380 gpu"]
  },
  {
    id: "intel-arc-a770",
    name: "Intel Arc A770",
    brand: "Intel",
    family: "Intel Arc",
    tier: "midrange discrete",
    vram: 16,
    score: 66,
    gaming: 68,
    ai: 46,
    releaseYear: 2022,
    aliases: ["arc a770", "intel arc a770", "a770 gpu"]
  }
];

export const UNKNOWN_GPU = {
  id: "unknown-gpu",
  name: "Unknown Hardware",
  brand: "Unknown",
  family: "Unknown",
  tier: "unknown",
  vram: 0,
  score: 0,
  gaming: 0,
  ai: 0,
  aliases: []
};
